name: GHA
on:
  push:
    branches-ignore:
      - main
    paths:
      - "products.json"
jobs:
  GHA:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Pull request HEAD
        id: checkout_pr_head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
