name: GHA
on:
  push:
    branches-ignore:
      - master
    paths:
      - "products.json"
jobs:
  GHA:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Pull request HEAD
        id: checkout_pr_head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: print-diff
        shell: bash
        run: |
          git fetch origin master
          git diff origin/master..HEAD > mydiff
          echo "mydiff = "
          cat mydiff
      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: npm install parse-git-diff
      - uses: actions/github-script@v4
        id: script
        with:
          script: return "Hello!"
          result-encoding: string
      - name: Get result
        run: echo "${{steps.script.outputs.result}}"
