name: GHA
on:
  push:
    branches-ignore:
      - master
    paths:
      - "products.json"
jobs:
  GHA:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Pull request HEAD
        id: checkout_pr_head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Get Changed Piece of code
        uses: Rahul-Chauhan-2212/git-diff-action@v2.6.0
        id: git-diff-action
        with:
          json_diff_file_output: diff.json
          raw_diff_file_output: diff.txt
          file_output_only: "true"
          search_path: ./configs

      # Print the diff in JSON format
      - name: print json diff
        env:
          DIFF: ${{ steps.git-diff-action.outputs.json-diff-path }}
        run: cat $DIFF
