name: GHA
on:
  push:
    branches-ignore:
      - master
    paths:
      - "products.json"
jobs:
  GHA:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Pull request HEAD
        id: checkout_pr_head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: print-diff
        shell: bash
        run: |
          git fetch origin main
          git diff origin/main..HEAD > mydiff
          echo "mydiff = "
          cat mydiff
